// ROOT
:tip-caption: 💡
:note-caption: ℹ️
:important-caption: ⚠️
:task-caption: 👨‍🔧
:source-highlighter: pygments
:toc: left
:toclevels: 3
:experimental:
:nofooter:

# Setup Instructions

On Toledo, a link should be provided to GitHub Classroom. Go there and accept the assignment. This will create your private fork (= copy) of this repository.
You will be given the URL to this fork, which you can use to clone the forked repository to your laptop:

[source,bash]
----
# Needs to happen only once
$ git clone URL gomoku
----

where `URL` is replaced by the URL of your fork.
This will create a directory `gomoku` and download the repository to that location.

[IMPORTANT]
====
Regularly push your project code to GitHub.

This is a safety measure against technical mishaps.
If you were to lose your hard work and have failed to push your code frequently, expect no compassion from us.
====

## Receiving Updates

In order to receive updates, you need to link your repository to my original repository.

[source,bash]
----
# Needs to happen only once
$ git remote add upstream https://github.com/UCLeuvenLimburg/gomoku-starter
----

New updates can now be retrieved using

[source,bash]
----
# Needs to happen for each update
$ git pull upstream master
----

[IMPORTANT]
====
It is your responsibility to download updates as they become available.
You can ask GitHub to notify you whenever an update is made to the repository using the watch functionality (top right corner) provided on the https://github.com/UCLeuvenLimburg/gomoku-starter[repository's website].
====

## Compiling the Documentation

The documentation related to this project is included in the repository.
It has been written in the asciidoc which should be compiled to html format.
You can read the documentation as follows:

* Some are okay reading the asciidoc files in raw form.
  Of all the options listed here, this is the least reader friendly.
* GitHub can convert asciidoc to html for you.
  This means you can consult the documentation using GitHub's website.
  However, GitHub does not support all of asciidoc's features, causing readability to suffer.
* You can compile the asciidoc files to html yourself by following the instructions below.
  This leads you to have the documentation in their most readable form.

To compile the documentation yourself, start with installing https://www.ruby-lang.org/en/downloads/[Ruby].
Next, install the necessary gems (= Ruby packages)

[source,bash]
----
# Needs to happen only once
$ gem install asciidoctor
----

To actually build the documentation, run the following command in your repo's root directory (it contains `Rakefile`).

[source,bash]
----
# Needs to happen after every update
$ rake
----
